project_name: diffkeeper

before:
  hooks:
    - make build-ebpf

builds:
  - id: diffkeeper
    main: ./main.go
    binary: diffkeeper
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
    flags:
      - -trimpath

archives:
  - format: tar.gz
    builds: [diffkeeper]
    files:
      - README.md
      - LICENSE
      - ebpf/diffkeeper.bpf.c
      - ebpf/diffkeeper.bpf.o

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github

release:
  prerelease: auto
