name: Release Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build Windows binaries
        run: |
          make build-windows-amd64
          make build-windows-arm64
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: bin/diffkeeper-windows-*
