name: CI
on: [push, pull_request]
permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23']
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: docker/setup-buildx-action@v3
        id: buildx
      - run: make build-ebpf
      - run: make build
      - run: go test ./... -v
      - run: go test -tags integration ./... -v
      - name: Login to GHCR
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'saworbit' && matrix.platform == 'amd64'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push image
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'saworbit' && matrix.platform == 'amd64'
        run: |
          docker buildx build \
            --builder ${{ steps.buildx.outputs.name }} \
            --platform linux/${{ matrix.platform }} \
            -t ghcr.io/${{ github.repository_owner }}/diffkeeper:ci \
            --push .
